### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by bhogeswar** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#12]
Dear  Kaushik,

Today I tried to find stock forecasting opensource projects in python came across many but due to some or other issue many programs are not able to run(deprecated), during the course i found your project and details are very clear and thought of giving a try and it worked perfect in the first try itself., UI is very easy to use and the results populated with much ease compared to other programs, thank you very much for sharing such a valuable project to the public but i will evaluate the predictions during next week.
In between i found some issue with the main.py program it gives below error on each new scrip search, i end up closing the console and run again it works, if possible can you provide me any updated python scripts to fix this issue?

Do we expect any future upgrade on predictions to show next day high and low prices aswell?

Error message:

Exception ignored in: <function Image.__del__ at 0x000002288D1DAB80>
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 4014, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000002288D1DAB80>
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 4014, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

Regards,
bhogeswar@gmail.com

**Comment by ponragul** [comment]
did you get the forcast report

**Comment by 0543139448** [comment]
> Dear Kaushik,
> 
> Today I tried to find stock forecasting opensource projects in python came across many but due to some or other issue many programs are not able to run(deprecated), during the course i found your project and details are very clear and thought of giving a try and it worked perfect in the first try itself., UI is very easy to use and the results populated with much ease compared to other programs, thank you very much for sharing such a valuable project to the public but i will evaluate the predictions during next week.
> In between i found some issue with the main.py program it gives below error on each new scrip search, i end up closing the console and run again it works, if possible can you provide me any updated python scripts to fix this issue?
> 
> Do we expect any future upgrade on predictions to show next day high and low prices aswell?
> 
> Error message:
> 
> Exception ignored in: <function Image.**del** at 0x000002288D1DAB80>
> Traceback (most recent call last):
> File "C:\Python38\lib\tkinter__init__.py", line 4014, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Exception ignored in: <function Image.**del** at 0x000002288D1DAB80>
> Traceback (most recent call last):
> File "C:\Python38\lib\tkinter__init__.py", line 4014, in **del**
> self.tk.call('image', 'delete', self.name)
> RuntimeError: main thread is not in main loop
> Tcl_AsyncDelete: async handler deleted by the wrong thread
> 
> Regards,
> [bhogeswar@gmail.com](mailto:bhogeswar@gmail.com)

Hi there,
Have you found a solution to this error?
