### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by trollssqwer** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#15]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/macbook/Downloads/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis-master/main.py", line 475, in insertintotable
    polarity,tw_list,tw_pol,pos,neg,neutral = retrieving_tweets_polarity(quote)
  File "/Users/macbook/Downloads/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis-master/main.py", line 368, in retrieving_tweets_polarity
    for sentence in blob.sentences:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textblob/decorators.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textblob/blob.py", line 639, in sentences
    return self._create_sentence_objects()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textblob/blob.py", line 683, in _create_sentence_objects
    sentences = sent_tokenize(self.raw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textblob/base.py", line 64, in itokenize
    return (t for t in self.tokenize(text, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/textblob/decorators.py", line 38, in decorated
    raise MissingCorpusError()
textblob.exceptions.MissingCorpusError: 
Looks like you are missing some required data for this feature.

**Comment by Rajat1206** [comment]
@kaushikjadhav01 can you please look at this issue?

Thanks!

**Comment by kssuprith** [comment]
Did you get any updates for this issue

**Comment by habib-m-ahmed** [comment]
@kaushikjadhav01 @kssuprith @Rajat1206 Did any of you manage to figure out this issue? I am having the same problem
